import type {Metadata} from "next"
import {siteConfig} from "@/lib/site"

export const metadata: Metadata = {
  title: {absolute: "Affiliate Partnerships | The Bloxline"},
  description: "Partner with The Bloxline through affiliate and referral opportunities across Roblox analytics, development, education, gaming, community tools and studio services.",
  alternates: {canonical: "/affiliates"},
  openGraph: {title: "Partner with The Bloxline", description: "Affiliate and referral partnerships for companies serving Roblox players, parents, developers, studios and brands.", url: "/affiliates", type: "website"},
}

const categories = [
  {title: "Roblox analytics and intelligence", examples: ["Roblox market intelligence platforms", "Game analytics tools", "Audience research platforms", "Competitive intelligence", "Brand intelligence", "Virtual world intelligence", "Player behaviour analysis", "Trend analysis"], copy: "Useful for Roblox studios, agencies, brands, investors and businesses trying to understand the wider Roblox market."},
  {title: "Roblox development tools", examples: ["Developer software", "Coding tools", "AI development tools", "3D modelling", "Animation", "Audio tools", "Testing tools", "Development platforms"], copy: "Useful for developers and studios building Roblox experiences."},
  {title: "Studio and business software", examples: ["Project management", "Team collaboration", "Remote working", "Developer productivity", "Product analytics", "Feedback software", "Research platforms", "Business intelligence"], copy: "Useful for professional Roblox studios and growing development teams."},
  {title: "Community tools", examples: ["Community management", "Discord bots", "Moderation software", "Player feedback", "Social community tools", "Community analytics"], copy: "Particularly relevant because The Bloxline also works directly with Roblox studios around community building."},
  {title: "Creator and influencer platforms", examples: ["Creator discovery", "Influencer software", "Gaming creator marketplaces", "Campaign management", "Creator analytics", "UGC platforms"], copy: "Useful for Roblox studios and brands looking to reach players through creators."},
  {title: "Roblox education and coding", examples: ["Roblox Studio courses", "Luau courses", "Coding education", "Game development", "3D modelling", "Children's coding", "Adult learning", "STEM education"], copy: "Useful for players and parents interested in turning a passion for Roblox into practical creative and technical skills."},
  {title: "Parent and family technology", examples: ["Online safety", "Parental controls", "Family technology", "Account security", "Password managers", "Digital literacy"], copy: "Useful for parents trying to help children use Roblox responsibly.", note: "The Bloxline does not use fear based messaging to promote safety products. Any partnership in this category must genuinely help families make informed choices."},
  {title: "Gaming and creator equipment", examples: ["Gaming PCs", "Gaming laptops", "Controllers", "Keyboards", "Mice", "Headsets", "Microphones", "Webcams", "Lighting", "Streaming equipment"], copy: "Useful for adult Roblox players, developers and creators."},
  {title: "Recruitment and talent", examples: ["Gaming recruitment", "Roblox recruitment", "Job boards", "Freelance marketplaces", "Talent sourcing", "Recruitment software"], copy: "Useful for Roblox studios hiring developers, artists, designers and community managers."},
  {title: "Roblox services", examples: ["Localisation", "QA", "Game testing", "User acquisition", "Creator marketing", "Development support", "Studio consulting", "Market research", "Player research"], copy: "Useful for studios looking for specialist partners."},
  {title: "Books and learning resources", examples: ["Roblox books", "Programming books", "Game design books", "Educational resources", "Digital learning"], copy: "Useful for aspiring developers, educators and parents."},
  {title: "Roblox related consumer products", examples: ["Roblox gift cards", "Gaming accessories", "Official Roblox merchandise", "Licensed products"], copy: "Consumer partnerships should remain directly connected to Roblox."},
]

const audiences = ["Adult Roblox players", "Parents", "Aspiring developers", "Roblox developers", "Studio founders", "Community teams", "Brands", "Agencies", "Investors", "Educators", "Businesses trying to understand Roblox"]

export default function AffiliatesPage() {
  const partnershipEmail = `mailto:${siteConfig.commercialEmail}?subject=${encodeURIComponent("Affiliate Partnership Enquiry")}`

  return <>
    <header className="service-page-hero affiliate-hero"><div className="container"><span className="eyebrow">Affiliate Partnerships</span><h1>Partner with The Bloxline</h1><p>The Bloxline works with Roblox players, parents, developers, studios, brands and businesses trying to understand or participate in the Roblox ecosystem.</p><p>We are open to affiliate and referral partnerships with companies whose products or services are genuinely useful to those audiences.</p><p>If your business fits one of the categories below, we would be interested in hearing from you.</p><a className="button" href={partnershipEmail}>Discuss a Partnership</a><p className="affiliate-note">We review every opportunity individually and only promote products or services that make sense for The Bloxline audience.</p></div></header>

    <section className="affiliate-categories"><div className="container"><div className="agency-section-head"><span className="eyebrow">Who we work with</span><h2>Partnership categories</h2><p>The Bloxline covers a broad part of the Roblox ecosystem, from people playing and learning about Roblox to the studios, developers and brands building businesses around it.</p><p>Because of that, we are open to affiliate and referral partnerships across several relevant categories.</p></div><div className="affiliate-category-grid">{categories.map((category) => <article className="affiliate-category-card" key={category.title}><h3>{category.title}</h3><ul>{category.examples.map((item) => <li key={item}>{item}</li>)}</ul><p>{category.copy}</p>{category.note && <p className="affiliate-category-note">{category.note}</p>}</article>)}</div></div></section>

    <section className="affiliate-relevance"><div className="container agency-proof-grid"><div><span className="eyebrow">Relevance matters</span><h2>Useful partnerships come first.</h2></div><div><p>The Bloxline is not interested in promoting products simply because an affiliate commission exists.</p><p>We want partnerships that genuinely make sense for our readers, clients and wider Roblox audience.</p><p>Generally we are not looking for:</p><ul><li>Unrelated consumer products</li><li>Low quality gaming merchandise</li><li>Gambling</li><li>Cryptocurrency schemes</li><li>Get rich quick products</li><li>Misleading financial products</li><li>Products exploiting children</li><li>Aggressive subscription services</li><li>Misleading advertising</li></ul><p>All partnerships remain subject to editorial and commercial review.</p></div></div></section>

    <section className="affiliate-how container"><div className="agency-section-head"><span className="eyebrow">How we can work together</span><h2>Partnerships designed around the right audience.</h2></div><div className="affiliate-work-grid"><article><h3>Relevant articles</h3><p>Helpful products and services can be included in appropriate editorial coverage where they genuinely add value.</p></article><article><h3>Guides and resources</h3><p>Useful tools may be recommended within practical guides built for parents, developers, studios and adult Roblox audiences.</p></article><article><h3>Bloxline for Studios</h3><p>Partnerships can support the commercial services offered to Roblox developers and studios.</p></article><article><h3>Parent and adult guides</h3><p>Relevant products can reach adults who want straightforward help understanding Roblox.</p></article><article><h3>Social content</h3><p>Suitable partnerships can be discussed through Bloxline social content when the format is right for the audience.</p></article><article><h3>Referral partnerships</h3><p>Referral programmes can introduce relevant tools and services directly to the people who may benefit from them.</p></article></div><p className="affiliate-closing-copy">The exact partnership structure depends on the product, audience and commercial arrangement.</p></section>

    <section className="affiliate-current"><div className="container"><div className="agency-section-head"><span className="eyebrow">Current partnerships</span><h2>GEEIQ</h2><p>GEEIQ provides intelligence and insights around virtual worlds, gaming audiences and platforms including Roblox.</p></div></div></section>

    <section className="affiliate-audience container"><div className="agency-section-head"><span className="eyebrow">Who The Bloxline reaches</span><h2>A Roblox audience with different needs.</h2></div><div className="audience-chip-grid">{audiences.map((audience) => <div key={audience}>{audience}</div>)}</div><p>Different partnerships are relevant to different parts of our audience.</p></section>

    <section className="affiliate-transparency"><div className="container agency-proof-grid"><div><span className="eyebrow">Transparency matters</span><h2>Commercial relationships do not control the content.</h2></div><div><p>Some links may generate commissions.</p><p>Affiliate relationships are disclosed.</p><p>Affiliate relationships never determine editorial coverage.</p><p>The Bloxline remains free to criticise, compare or decline to recommend partners.</p><p>Commercial relationships should support the content rather than control it.</p></div></div></section>

    <section className="agency-final affiliate-final"><div className="container"><h2>Interested in partnering with The Bloxline?</h2><p>If your product or service is relevant to Roblox players, parents, developers, studios or businesses operating around Roblox, we would love to hear from you.</p><p>Tell us what your product does, who it is for, how your affiliate programme works and the partnership you are interested in.</p><a className="button" href={partnershipEmail}>Discuss an Affiliate Partnership</a></div></section>
  </>
}
