import type {Metadata} from "next"
import Link from "next/link"
import {siteConfig} from "@/lib/site"

export const metadata: Metadata = {title: "Terms", description: "Initial terms for using The Bloxline.", alternates: {canonical: "/terms"}}

export default function TermsPage() {
  return <article className="legal"><span className="eyebrow">Legal template</span><h1>Terms</h1><p><strong>Last reviewed:</strong> 17 August 2026. These terms are an initial template and require legal review.</p><h2>Editorial information</h2><p>The Bloxline provides general editorial information. It is not legal, financial, safeguarding or investment advice. Readers should check important decisions against appropriate professional or official sources.</p><h2>Affiliate relationships</h2><p>Some links on The Bloxline are affiliate links. The Bloxline may receive a payment when a reader follows a marked link and completes a qualifying action. Affiliate relationships do not guarantee that a third party application will be accepted or that a product, service or commercial opportunity will produce a particular result.</p><p>The GEEIQ Integration Network referral relationship is explained in the <Link className="text-link" href="/developer-network#affiliate-disclosure">affiliate disclosure</Link>.</p><h2>Third party services</h2><p>Third party websites, programmes and services have their own terms, privacy practices and application decisions. Readers should review those terms before providing information or entering an agreement.</p><h2>Intellectual property</h2><p>Unless otherwise stated, original Bloxline writing and branding may not be republished without permission. Third party names and trade marks remain the property of their owners.</p><h2>Independence</h2><p>{siteConfig.disclaimer}</p></article>
}
